package org.nodescope.android.feature.channels

import android.content.Intent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardCapitalization
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import org.nodescope.android.core.design.HealthyGreen
import org.nodescope.android.core.design.rememberCopyAction
import org.nodescope.android.core.model.MonitoredChannel
import org.nodescope.android.core.storage.ChannelMonitorException
import org.nodescope.android.core.storage.MonitoredChannelStore

private enum class AddMode(val label: String, val title: String, val icon: ImageVector) {
    HASHTAG("Hashtag", "Monitor a hashtag", Icons.Outlined.Tag),
    PRIVATE("Private", "Add a private key", Icons.Outlined.Key),
    GENERATE("Generate", "Generate a private channel", Icons.Outlined.AutoAwesome),
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddChannelScreen(store: MonitoredChannelStore, onDone: () -> Unit) {
    var mode by rememberSaveable { mutableStateOf(AddMode.HASHTAG) }
    var hashtag by rememberSaveable { mutableStateOf("") }
    // Key material is deliberately not saved into instance state.
    var keyHex by remember { mutableStateOf("") }
    var label by rememberSaveable { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }
    var generated by remember { mutableStateOf<MonitoredChannel?>(null) }
    val canSave = when (mode) {
        AddMode.HASHTAG -> hashtag.isNotBlank()
        AddMode.PRIVATE -> keyHex.isNotBlank()
        AddMode.GENERATE -> generated == null
    }
    fun save() {
        error = null
        try {
            when (mode) {
                AddMode.HASHTAG -> { store.monitorHashtag(hashtag); onDone() }
                AddMode.PRIVATE -> { store.monitorKey(keyHex, label); keyHex = ""; onDone() }
                AddMode.GENERATE -> generated = store.generate(label)
            }
        } catch (e: ChannelMonitorException) { error = e.message }
    }

    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp), verticalArrangement = Arrangement.spacedBy(18.dp)) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(14.dp)) {
            Surface(color = MaterialTheme.colorScheme.primaryContainer, shape = MaterialTheme.shapes.medium) {
                Icon(Icons.Outlined.Shield, null, Modifier.padding(12.dp).size(26.dp), tint = MaterialTheme.colorScheme.onPrimaryContainer)
            }
            Column {
                Text("Listen to a channel", style = MaterialTheme.typography.titleLarge)
                Text("Keys are processed and stored on this device.", style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }
        SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
            AddMode.entries.forEachIndexed { index, option ->
                SegmentedButton(selected = mode == option, onClick = { mode = option; error = null; generated = null },
                    shape = SegmentedButtonDefaults.itemShape(index, AddMode.entries.size),
                    icon = { SegmentedButtonDefaults.Icon(mode == option) { Icon(option.icon, null, Modifier.size(18.dp)) } }) { Text(option.label) }
            }
        }
        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                Text(mode.title, style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)
                val plain = KeyboardOptions(capitalization = KeyboardCapitalization.None, autoCorrectEnabled = false, imeAction = ImeAction.Done)
                when (mode) {
                    AddMode.HASHTAG -> {
                        OutlinedTextField(hashtag, { hashtag = it }, Modifier.fillMaxWidth(), label = { Text("Channel name") },
                            placeholder = { Text("#wardriving") }, singleLine = true, keyboardOptions = plain)
                        Text("NodeScope derives the public hashtag key and decrypts matching traffic locally.",
                            style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                    AddMode.PRIVATE -> {
                        OutlinedTextField(keyHex, { keyHex = it }, Modifier.fillMaxWidth(), label = { Text("32-character hexadecimal key") },
                            singleLine = true, textStyle = LocalTextStyle.current.copy(fontFamily = FontFamily.Monospace),
                            keyboardOptions = plain.copy(keyboardType = KeyboardType.Password))
                        OutlinedTextField(label, { label = it }, Modifier.fillMaxWidth(), label = { Text("Display name (optional)") }, singleLine = true)
                    }
                    AddMode.GENERATE -> {
                        OutlinedTextField(label, { label = it }, Modifier.fillMaxWidth(), label = { Text("Display name (optional)") },
                            singleLine = true, enabled = generated == null)
                        Text("A cryptographically secure key is generated on this device. Share it only with trusted participants.",
                            style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                }
                error?.let { Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall) }
            }
        }
        generated?.let { GeneratedKey(it) }
        Surface(color = HealthyGreen.copy(alpha = 0.10f), shape = MaterialTheme.shapes.medium) {
            Row(Modifier.padding(14.dp), horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                Icon(Icons.Outlined.PhonelinkLock, null, tint = MaterialTheme.colorScheme.onSurfaceVariant)
                Text("Channel keys are encrypted on this device and never sent to an analyzer or included in backups. NodeScope listens to traffic but cannot transmit over radio.",
                    style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }
        if (generated == null) Button(onClick = ::save, enabled = canSave, modifier = Modifier.fillMaxWidth().heightIn(min = 52.dp)) {
            Text(if (mode == AddMode.GENERATE) "Generate secure channel" else "Monitor channel")
        } else Button(onClick = onDone, modifier = Modifier.fillMaxWidth().heightIn(min = 52.dp)) { Text("Done") }
    }
}

@Composable
private fun GeneratedKey(channel: MonitoredChannel) {
    val copy = rememberCopyAction()
    val context = LocalContext.current
    Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)) {
        Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            Text("Generated key for ${channel.title}", style = MaterialTheme.typography.titleMedium)
            Surface(color = MaterialTheme.colorScheme.surfaceContainer, shape = MaterialTheme.shapes.small) {
                Text(channel.keyHex, Modifier.fillMaxWidth().padding(12.dp), fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodyMedium)
            }
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedButton(onClick = { copy("Channel key", channel.keyHex, true) }, Modifier.weight(1f)) {
                    Icon(Icons.Outlined.ContentCopy, null, Modifier.size(18.dp)); Spacer(Modifier.width(6.dp)); Text("Copy key")
                }
                OutlinedButton(onClick = {
                    context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).setType("text/plain")
                        .putExtra(Intent.EXTRA_TEXT, channel.keyHex).putExtra(Intent.EXTRA_SUBJECT, "Private MeshCore channel key"), "Share channel key"))
                }, Modifier.weight(1f)) {
                    Icon(Icons.Outlined.Share, null, Modifier.size(18.dp)); Spacer(Modifier.width(6.dp)); Text("Share")
                }
            }
        }
    }
}
